### ISSUE TITLE
STL: Finish replacing tag dispatch with `if constexpr`

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#189]
Tag dispatch is the STL's original metaprogramming technique: overload a helper function on a tag struct (e.g. `input_iterator_tag` versus `forward_iterator_tag`, or `true_type` versus `false_type`) and then call it with a tag object to select the appropriate overload. This has several downsides, though - it is somewhat verbose, it interferes with code organization, and it results in actual function calls in debug mode. (This is slower, more work to step through when debugging, and bloats object files.) C++17 `if constexpr` supersedes tag dispatch in almost every situation (see note below) and we're using it in new C++17-and-later code. We can use it in C++14 mode too, but guarded with `_HAS_IF_CONSTEXPR` (C1XX, Clang, and EDG support it unconditionally with a suppressible warning; CUDA 10.1 Update 2 added identical support, but we aren't yet requiring that version).

We should finish overhauling the STL to use `if constexpr`. Whenever we decide to begin requiring CUDA 10.1 Update 2 or later, we can drop `_HAS_IF_CONSTEXPR` completely.

Note: Tag dispatch works with delegating constructors, whereas `if constexpr` works only in function bodies.

**Comment by StephanTLavavej** [comment]
In #491, I noticed that C++17 `default_searcher` is using tag dispatch when it could use `if constexpr`:
https://github.com/microsoft/STL/blob/ff947563da6511270d8b7292e162f8549df8267f/stl/inc/functional#L1662-L1664

**Comment by CaseyCarter** [comment]
#1433 brought `_Lex_compare_memcmp_classify` to our attention:

https://github.com/microsoft/STL/blob/60d9ed7ef4dcb7c3ec2d502bdb4b50123ae1c74b/stl/inc/xutility#L5303-L5319

This overload set could be `if constexpr`-ed to good effect, doubly so after #1433 adds more overloads to the set.

**Comment by AlexGuteniev** [comment]
https://github.com/microsoft/STL/issues/189#issuecomment-631298439:

> In #491, I noticed that C++17 `default_searcher` is using tag dispatch when it could use `if constexpr`:
> 
> https://github.com/microsoft/STL/blob/ff947563da6511270d8b7292e162f8549df8267f/stl/inc/functional#L1662-L1664

This is currently covered by #2219 , can be extracted to a separate change

----

https://github.com/microsoft/STL/issues/189#issuecomment-738499686:
> #1433 brought `_Lex_compare_memcmp_classify` to our attention:
> 
> https://github.com/microsoft/STL/blob/60d9ed7ef4dcb7c3ec2d502bdb4b50123ae1c74b/stl/inc/xutility#L5303-L5319
> 
> This overload set could be `if constexpr`-ed to good effect, doubly so after #1433 adds more overloads to the set.

This was addressed by #2158

**Comment by AlexGuteniev** [comment]
There's `_Seed` in `<random>`:

https://github.com/microsoft/STL/blob/86e22c3cf3238fa9aca10e47665f4c2b88b27206/stl/inc/random#L693-L702

**Comment by StephanTLavavej** [comment]
#2479 updated `basic_string_view` and `basic_string`'s `find_first_of`, with the remaining functions being:

* [ ] `find_last_of`
* [ ] `find_first_not_of`
* [ ] `find_last_not_of`

**Comment by StephanTLavavej** [comment]
Dispatching on iterator strength:

* [x] `vector::_Insert_range()` (fixed by #1794)
  https://github.com/microsoft/STL/blob/f099e9c9f91187376e85385b135ac62ef933e54f/stl/inc/vector#L1027-L1166
* [x] `vector::_Assign_range()` (fixed by #1794)
  https://github.com/microsoft/STL/blob/f099e9c9f91187376e85385b135ac62ef933e54f/stl/inc/vector#L1236-L1315
* [x] `vector<bool>::_Insert()` (fixed by #2694)
  https://github.com/microsoft/STL/blob/f099e9c9f91187376e85385b135ac62ef933e54f/stl/inc/vector#L3089-L3104

**Comment by AlexGuteniev** [comment]
There are candidates in `<format>` but not sure if it worth to untag dispatch them.

https://github.com/microsoft/STL/blob/bd3d740ae5de7255c720b8133c5d23aa131e0760/stl/inc/format#L1721-L1743
