### ISSUE TITLE
June 2021 LWG issues

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#1965]
(Previous meta-issue: #1679)

At the June 2021 virtual plenary meeting, the following LWG issues were resolved in the C++ Working Paper.

:grey_question: Not yet analyzed
===
* All done! :smiley_cat:

For each of these issues, we've determined whether they are:

:heavy_multiplication_x: Not applicable
===
If an issue requires no action from implementers, we mark it as N/A. Categories:

* Pure wording clarifications with nothing to implement (these can be changes to non-normative text like examples and informative notes, or wording cleanups to normative text that don't impact observable behavior)
  * [x] LWG-2997 LWG-491 and the specification of `{forward_,}list::unique`
  * [x] LWG-3521 Overly strict requirements on `qsort` and `bsearch`
  * [x] LWG-3526 Return types of `uses_allocator_construction_args` unspecified
* Something that increases the restrictions placed on users, but implementers aren't expected to enforce those restrictions
* Fixes for obviously broken wording, where implementers would have done the right thing anyways
  * [x] LWG-2818 "`::std::`" everywhere rule needs tweaking
  * [x] LWG-3462 Formatter requirements forbid use of `fc.arg()`
  * [x] LWG-3551 `borrowed_{iterator,subrange}_t` are overspecified

:smile_cat: Already implemented
===
Sometimes we cite LWG issues in product code comments as we're implementing their proposed resolutions. When the resolutions are officially accepted, we should remove the citations (as the default assumption is that we're implementing what the Standard says). If something is especially subtle, we can convert the citation to mention the relevant Standard section.

Sometimes we should add test coverage - e.g. when the Standard begins requiring something that we were already doing, but weren't explicitly testing for.

* Already implemented, comments need to be removed and messages need to cite the Standard
  * [x] LWG-3481 `viewable_range` mishandles lvalue move-only views (Removal in #1967)
  * [x] LWG-3517 `join_view::`*`iterator`*'s `iter_swap` is underconstrained (Removal in #1967)
  * [x] LWG-3523 `iota_view::`*`sentinel`* is not always `iota_view`'s sentinel (Removal in #1967)
  * [x] LWG-3530 *`BUILTIN-PTR-MEOW`* should not opt the type out of syntactic checks (Filed as #2182)
  * [x] LWG-3532 `split_view<V, P>::`*`inner-iterator`*`<true>::operator++(int)` should depend on *`Base`* (Removal in #1967)
  * [x] LWG-3543 Definition of when `counted_iterator`s refer to the same sequence isn't quite right (Filed as #2184)

* Implemented without comments
  * [x] LWG-3410 `lexicographical_compare_three_way` is overspecified
  * [x] LWG-3430 `std::fstream` & co. should be constructible from `string_view` (Implemented in #1968)
  * [x] LWG-3506 Missing allocator-extended constructors for `priority_queue` (Implemented in #1994)
  * [x] LWG-3518 Exception requirements on char trait operations unclear (Implemented in #2080)
  * [x] LWG-3522 Missing requirement on `InputIterator` template parameter for `priority_queue` constructors (Implemented in #1994)
  * [x] LWG-3529 `priority_queue(first, last)` should construct `c` with `(first, last)`
  * [x] LWG-3533 Make `base() const &` consistent across iterator wrappers that support `input_iterator`s (Implemented in #1993)
  * [x] LWG-3536 Should `chrono::from_stream()` assign zero to `duration` for failure? (Implemented in #2037)
  * [x] LWG-3539 `format_to` must not copy models of `output_iterator<const charT&>`
  * [x] LWG-3540 There should be no `const` in `basic_format_arg(const T* p)`
  * [x] LWG-3541 `indirectly_readable_traits` should be SFINAE-friendly for all types (Implemented in #1992)
  * [x] LWG-3542 `basic_format_arg` mis-handles `basic_string_view` with custom traits
  * [x] LWG-3544 *`format-arg-store`*`::args` is unintentionally not exposition-only
  * [x] LWG-3548 `shared_ptr` construction from `unique_ptr` should move (not copy) the deleter (Implemented in #2007)
  * [x] LWG-3553 Useless constraint in `split_view::`*`outer-iterator`*`::value_type::begin()` (Implemented in #1990)
  * [x] LWG-3555 `{transform,elements}_view::`*`iterator`*`::iterator_concept` should consider `const`-qualification of the underlying range (Implemented in #1989)

:adhesive_bandage: Patches an unimplemented feature
===
We should record this LWG issue in the GitHub issue tracking the feature. That way, we'll remember to verify it, but it doesn't represent net new work.
* [x] LWG-3552 Parallel specialized memory algorithms should require forward iterators (Mentioned in #525)

:lady_beetle: Not yet implemented
===
* PRs out for review:
  * [x] LWG-2774 `std::function` construction vs assignment (Implemented in #2098)
  * [x] LWG-3528 `make_from_tuple` can perform (the equivalent of) a C-style cast (Implemented in #2160)
  * [x] LWG-3546 `common_iterator`'s *`postfix-proxy`* is not quite right (Implemented in #1991)
* We should file a [GitHub issue labeled **LWG**](https://github.com/microsoft/STL/issues?q=is%3Aissue+label%3ALWG); see those existing examples.
  * [x] LWG-3519 Incomplete synopses for `<random>` classes (Filed as #2179)
  * [x] LWG-3520 `iter_move` and `iter_swap` are inconsistent for `transform_view::`*`iterator`* (Filed as #2180)
  * [x] LWG-3527 `uses_allocator_construction_args` handles rvalue pairs of rvalue references incorrectly (Filed as #2181)
  * [x] LWG-3549 `view_interface` is overspecified to derive from `view_base` (Filed as #2178)

**Comment by SuperWig** [comment]
The only LWG issue cited in the code base, other than the ones mentioned in that PR I just submitted, is LWG-3536.

**Comment by cpplearner** [comment]
>  LWG-3539 `format_to` must not copy models of `output_iterator<const charT&>`

Already implemented in #1795 

>  LWG-3540 There should be no `const` in `basic_format_arg(const T* p)`

Already implemented in #1867

**Comment by CaseyCarter** [comment]
LWG-2818 is a pure wording change; there's nothing to implement.

**Comment by MattStephanson** [comment]
LWG-3536 is tracked (and was prompted) by #1740.

**Comment by miscco** [comment]
LWG-3552 does not apply as there are currently no parallel specialized memory algorithms

**Comment by miscco** [comment]
Created a PR for LWG-3555 here #1989

**Comment by miscco** [comment]
Regarding LWG-3551 I do not see any necessary changes. As far as I remember MSVC internally optimizes `conditional_t` away and we do not have an alternative mechanism at hand

**Comment by CaseyCarter** [comment]
Processed thread to here.

**Comment by CaseyCarter** [comment]
LWG-3548 is not yet implemented, but will be by #2007.

**Comment by StephanTLavavej** [comment]
@MattStephanson I haven't had a chance to review #2088 yet as the C++20 and C++23 PRs have taken priority - it is still on the list of things I intend to review though :smile_cat: (The rate of incoming PRs has slightly exceeded our rate of reviewing them, which has led to an increasing backlog.)

I tend to view the `tr1` classes as implementation details, which we retain for ABI and to avoid breaking legacy code (although we have deprecated them). The argument against extending recent Standard changes to them, is that we would be extrapolating the changes and that gives us the chance to get things wrong, or destabilize legacy code. The argument for would be that it would make the header more consistent, instead of appearing half-updated. I'd probably avoid extrapolating changes to `tr1` but if you wanted to, I wouldn't object as long as they didn't appear to be too disruptive.

**Comment by StephanTLavavej** [comment]
@frederick-vs-ja Thanks for analyzing the remaining issues! I agree with all of your conclusions, and have filed issues accordingly.

@MattStephanson I filed #2179, quoting the discussion here, so you can link your PR to it when you're ready.

Thanks everyone! All of the June 2021 LWG issues have either been resolved or properly tracked, so I'm closing this meta-issue.
