### ISSUE TITLE
October 2021 LWG issues

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2236]
(Previous meta-issue: #1965)

At the October 2021 virtual plenary meeting, the following LWG issues were resolved in the C++ Working Paper.

:grey_question: Not yet analyzed
===
* Analyzed all issues! :smile_cat:

:heavy_multiplication_x: Not applicable
===
If an issue requires no action from implementers, we mark it as N/A. Categories:

* Pure wording clarifications with nothing to implement (these can be changes to non-normative text like examples and informative notes, or wording cleanups to normative text that don't impact observable behavior)
  + [x] LWG-2191 Incorrect specification of `match_results(match_results&&)`
  + [x] LWG-3123 `duration` constructor from representation shouldn't be effectively non-throwing
  + [x] LWG-3152 `common_type` and `common_reference` have flaws in common
  + [x] LWG-3361 `safe_range<SomeRange&>` case
  + [x] LWG-3559 Semantic requirements of `sized_range` are circular
  + [x] LWG-3573 Missing *Throws* element for `basic_string_view(It begin, End end)`
* Something that increases the restrictions placed on users, but implementers aren't expected to enforce those restrictions
* Fixes for obviously broken wording, where implementers would have done the right thing anyways

:smile_cat: Already implemented
===
Sometimes we cite LWG issues in product code comments as we're implementing their proposed resolutions. When the resolutions are officially accepted, we should remove the citations (as the default assumption is that we're implementing what the Standard says). If something is especially subtle, we can convert the citation to mention the relevant Standard section.

Sometimes we should add test coverage - e.g. when the Standard begins requiring something that we were already doing, but weren't explicitly testing for.

* Already implemented, comments need to be removed and messages need to cite the Standard
* Implemented without comments
  + [x] LWG-2762 `unique_ptr` `operator*()` should be `noexcept` (implemented in #2376)
  + [x] LWG-3293 `move_iterator` `operator+()` has incorrect constraints (comments removed by #2269)
  + [x] LWG-3407 Some problems with the wording changes of [P1739R4](https://wg21.link/P1739R4) (comments removed by #2269)
  + [x] LWG-3422 Issues of `seed_seq`'s constructors (implemented in #2260)
  + [x] LWG-3480 `directory_iterator` and `recursive_directory_iterator` are not C++20 ranges (implemented in #2340)
  + [x] LWG-3498 Inconsistent `noexcept`-specifiers for `basic_syncbuf` (comments removed by #2269)
  + [x] LWG-3535 `join_view::`*`iterator`*`::iterator_category` and `::iterator_concept` lie (comments removed by #2269)
  + [x] LWG-3554 `chrono::parse` needs `const charT*` and `basic_string_view<charT>` overloads (implemented by #2261)
  + [x] LWG-3560 `ranges::equal` and `ranges::is_permutation` should short-circuit for `sized_range`s (implemented in the original PRs #565 and #892)
  + [x] LWG-3566 Constraint recursion for `operator<=>(optional<T>, U)` (comments removed by #2269)
  + [x] LWG-3567 Formatting move-only iterators, take two (implemented in original PR #1821)
  + [x] LWG-3568 `basic_istream_view` needs to initialize *`value_`* (comments removed by #2269)
  + [x] LWG-3572 *`copyable-box`* should be fully `constexpr` (implemented in #2012)
  + [x] LWG-3581 The range constructor makes `basic_string_view` not trivially move constructible (comments removed by #2269)
  + [x] LWG-3585 `variant` converting assignment with immovable alternative

:adhesive_bandage: Patches an unimplemented feature
===
We should record this LWG issue in the GitHub issue tracking the feature. That way, we'll remember to verify it, but it doesn't represent net new work.

:lady_beetle: Not yet implemented
===
* Filed a [GitHub issue labeled **LWG**](https://github.com/microsoft/STL/issues?q=is%3Aissue+label%3ALWG)
  + [x] LWG-2381 Inconsistency in parsing floating-point numbers (filed #2388)
  + [x] LWG-3121 `tuple` constructor constraints for `UTypes&&...` overloads (filed #2390)
  + [x] LWG-3146 Excessive unwrapping in `std::ref`/`cref` (filed #2391)
  + [x] LWG-3392 `ranges::distance()` cannot be used on a move-only iterator with a sized sentinel (filed #2392)
  + [x] LWG-3470 *`convertible-to-non-slicing`* seems to reject valid case (filed #2393)
  + [x] LWG-3557 The `static_cast` expression in `convertible_to` has the wrong operand (filed #2394)
  + [x] LWG-3561 Issue with internal counter in `discard_block_engine` (filed #2250)
  + [x] LWG-3563 `keys_view` example is broken (filed #2389)
  + [x] LWG-3570 `basic_osyncstream::emit` should be an unformatted output function (filed #2395)
  + [x] LWG-3571 `flush_emit` should set `badbit` if the `emit` call fails (filed #2396)
  + [x] LWG-3574 `common_iterator` should be completely `constexpr`-able (filed #2397)
  + [x] LWG-3580 `iota_view`'s `iterator`'s binary `operator+` should be improved (filed #2398)
  + [x] LWG-3589 The `const` lvalue reference overload of `get` for `subrange` does not constrain `I` to be `copyable` when `N == 0` (filed #2399)
  + [x] LWG-3590 `split_view::base() const &` is overconstrained (filed #2400)
  + [x] LWG-3591 `lazy_split_view<input_view>::`*`inner-iterator`*`::base() &&` invalidates outer iterators (filed #2401)
  + [x] LWG-3592 `lazy_split_view` needs to check the simpleness of `Pattern` (filed #2402)
  + [x] LWG-3593 Several iterators' `base() const &` and `lazy_split_view::`*`outer-iterator`*`::value_type::end()` missing `noexcept` (filed #2403)
  + [x] LWG-3595 Exposition-only classes *`proxy`* and *`postfix-proxy`* for `common_iterator` should be fully `constexpr` (filed #2264)
* PR out for review

**Comment by MattStephanson** [comment]
LWG-3561: This would involving changing `discard_block`'s internal `_Nx` counter and template arguments from `int` to `size_t`, which I think would be an ABI break. I think the most we could do now is add a `// TRANSITION, ABI` comment, and maybe a `static_assert` for `discard_block_engine` that its parameters must be <= `INT_MAX`.

**Comment by CaseyCarter** [comment]
> [LWG-3561](https://cplusplus.github.io/LWG/issue3561): This would involving changing `discard_block`'s internal `_Nx` counter and template arguments from `int` to `size_t`, which I think would be an ABI break. I think the most we could do now is add a `// TRANSITION, ABI` comment, and maybe a `static_assert` for `discard_block_engine` that its parameters must be <= `INT_MAX`.

I think we could greatly improve `discard_block_engine` by divorcing it completely from the TR1-era `discard_block`. We could even make it tolerate `p > INT_MAX`, but I agree that `r > INT_MAX` is not supportable without breaking ABI.

**Comment by timsong-cpp** [comment]
> > [LWG-3561](https://cplusplus.github.io/LWG/issue3561): This would involving changing `discard_block`'s internal `_Nx` counter and template arguments from `int` to `size_t`, which I think would be an ABI break. I think the most we could do now is add a `// TRANSITION, ABI` comment, and maybe a `static_assert` for `discard_block_engine` that its parameters must be <= `INT_MAX`.
> 
> I think we could greatly improve `discard_block_engine` by divorcing it completely from the TR1-era `discard_block`. We could even make it tolerate `p > INT_MAX`, but I agree that `r > INT_MAX` is not supportable without breaking ABI.

Couldn't you change the type of `_Nx` only if `r > INT_MAX`?

**Comment by MattStephanson** [comment]
> Couldn't you change the type of _Nx only if r > INT_MAX?

Let me create a new issue for LWG-3561 so that this meta-issue doesn't become too crowded

**Comment by AlexGuteniev** [comment]
* [x] LWG-2762 `unique_ptr` `operator*()` should be `noexcept` - filed #2257, `good-first-issue` candidate

**Comment by cpplearner** [comment]
Following issues are Already implemented:

LWG-3568 `basic_istream_view` needs to initialize `value_`

https://github.com/microsoft/STL/blob/dc888f7d9fb7a4db8d3441f9e9bac2e0c6ecc4db/stl/inc/ranges#L1355

LWG-3535 `join_view::`*`iterator`*`::iterator_category` and `::iterator_concept` lie

https://github.com/microsoft/STL/blob/dc888f7d9fb7a4db8d3441f9e9bac2e0c6ecc4db/stl/inc/ranges#L2967
https://github.com/microsoft/STL/blob/dc888f7d9fb7a4db8d3441f9e9bac2e0c6ecc4db/stl/inc/ranges#L3039

LWG-3498 Inconsistent `noexcept`-specifiers for `basic_syncbuf`

https://github.com/microsoft/STL/blob/dc888f7d9fb7a4db8d3441f9e9bac2e0c6ecc4db/stl/inc/syncstream#L109
https://github.com/microsoft/STL/blob/dc888f7d9fb7a4db8d3441f9e9bac2e0c6ecc4db/stl/inc/syncstream#L117

LWG-3581 The range constructor makes `basic_string_view` not trivially move constructible

https://github.com/microsoft/STL/blob/dc888f7d9fb7a4db8d3441f9e9bac2e0c6ecc4db/stl/inc/xstring#L1287

LWG-3293 `move_iterator` `operator+()` has incorrect constraints

https://github.com/microsoft/STL/blob/dc888f7d9fb7a4db8d3441f9e9bac2e0c6ecc4db/stl/inc/xutility#L3865

**Comment by cpplearner** [comment]
These seem to be Already implemented (some might be closer to the "Not applicable" side, e.g. LWG-3559):

>  LWG-2191 Incorrect specification of `match_results(match_results&&)`
>
>  LWG-2381 Inconsistency in parsing floating-point numbers
>
>  LWG-3123 `duration` constructor from representation shouldn't be effectively non-throwing
>
>  LWG-3152 `common_type` and `common_reference` have flaws in common
>
>  LWG-3559 Semantic requirements of `sized_range` are circular
>
>  LWG-3560 `ranges::equal` and `ranges::is_permutation` should short-circuit for `sized_range`s
>
>  LWG-3567 Formatting move-only iterators, take two
>
>  LWG-3572 *`copyable-box`* should be fully `constexpr`
>
>  LWG-3573 Missing Throws element for `basic_string_view(It begin, End end)`
>
>  LWG-3585 `variant` converting assignment with immovable alternative

**Comment by StephanTLavavej** [comment]
@cpplearner Thanks! I've updated the list accordingly with the results of your analysis. The one exception was LWG-2381 - I noticed it still needs implementation work, so I filed a tracking issue with a repro.

**Comment by StephanTLavavej** [comment]
Thanks everyone - this batch of LWG issues has been fully categorized! :tada:
