### ISSUE TITLE
February 2022 LWG issues

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#2527]
(Previous meta-issue: #2236)

At the February 2022 virtual plenary meeting, the following LWG issues were resolved in the C++ Working Paper.

:grey_question: Not yet analyzed
===

:x:  Not applicable
===
If an issue requires no action from implementers, we mark it as N/A. Categories:

* Pure wording clarifications with nothing to implement (these can be changes to non-normative text like examples and informative notes, or wording cleanups to normative text that don't impact observable behavior)
* Something that increases the restrictions placed on users, but implementers aren't expected to enforce those restrictions
* Fixes for obviously broken wording, where implementers would have done the right thing anyways
  * [X] LWG-3607 `contiguous_iterator` should not be allowed to have custom `iter_move` and `iter_swap` behavior
  * [X] LWG-3619 Specification of `vformat_to` contains ill-formed `formatted_size` calls

:smile_cat: Already implemented
===
Sometimes we cite LWG issues in product code comments as we're implementing their proposed resolutions. When the resolutions are officially accepted, we should remove the citations (as the default assumption is that we're implementing what the Standard says). If something is especially subtle, we can convert the citation to mention the relevant Standard section.

Sometimes we should add test coverage - e.g. when the Standard begins requiring something that we were already doing, but weren't explicitly testing for.

* Already implemented, comments need to be removed and messages need to cite the Standard
  * [x] LWG-3601 `common_iterator`'s *`postfix-proxy`* needs `indirectly_readable`
  * [x] LWG-3616 LWG-3498 seems to miss the non-member `swap` for `basic_syncbuf`
* Implemented without comments
  * [X] LWG-3088 `forward_list::merge` behavior unclear when passed `*this`
  * [X] LWG-3650 Are `std::basic_string`'s `iterator` and `const_iterator` constexpr iterators?
  * [X] LWG-3643 Missing `constexpr` in `std::counted_iterator`

:adhesive_bandage: Patches an unimplemented feature
===
We should record this LWG issue in the GitHub issue tracking the feature. That way, we'll remember to verify it, but it doesn't represent net new work.

:lady_beetle: Not yet implemented
===
* Filed a [GitHub issue labeled **LWG**](https://github.com/microsoft/STL/issues?q=is%3Aissue+label%3ALWG)
  * [X] LWG-3471 `polymorphic_allocator::allocate` does not satisfy *Cpp17Allocator* requirements (Filed #2550)
  * [X] LWG-3525 `uses_allocator_construction_args` fails to handle types convertible to `pair` (Filed #2551)
  * [X] LWG-3598 `system_category().default_error_condition(0)` is underspecified (filed #2552)
  * [X] LWG-3612 Inconsistent pointer alignment in `std::format` (filed #2553)
  * [X] LWG-3618 Unnecessary `iter_move` for `transform_view::iterator` (filed #2554)
  * [X] LWG-3648 `format` should not print `bool` with `'c'` (filed #2555)
  * [X] LWG-3657 `std::hash<std::filesystem::path>` is not enabled (filed #2556)
* PR out for review
  * [ ] LWG-3610 `iota_view::size` sometimes rejects integer-class types (implemented in #2542)
  * [ ] LWG-3621 Remove feature-test macro `__cpp_lib_monadic_optional` (implemented in #2543)
  * [ ] LWG-3632 `unique_ptr` "*Mandates:* This constructor is not selected by class template argument deduction" (implemented in #2548)
  * [ ] LWG-3654 `basic_format_context::arg(size_t)` should be `noexcept` (implemented in #2528)
  * [ ] LWG-3661 `constinit atomic<shared_ptr<T>> a(nullptr);` should work (implemented in #2544)
  * [ ] LWG-3660 `iterator_traits<common_iterator>::pointer` should conform to `[iterator.traits]` (implemented in #2549)

**Comment by fsb4000** [comment]
[LWG-3643](https://cplusplus.github.io/LWG/lwg-active.html#3643) has been already implemented:
https://github.com/microsoft/STL/blob/bbd5dbaa61f192b393d12ea75a2dae1b8a014e7a/stl/inc/iterator#L1177-L1181

**Comment by frederick-vs-ja** [comment]
Personal analyzation:

## ❌ Not applicable
- LWG-3607 (only relaxes restrictions for implementations and strengthen restrictions for users)
- LWG-3619 (wording fixes only)
- LWG-3632 (wording fixes; also implemented in an alternative way)

## 😸 Already implemented
- With comment
  - LWG-3601
  - LWG-3616
- Without comment
  - LWG-3088
  - LWG-3650
  - LWG-3660 the condition whether `decltype(a.operator->())` is used seems implemented incorrectly, fix may be needed

## 🐞 Not yet implemented
- LWG-3471 may be N/A, if no related lifetime-based optimization is available
- LWG-3525
- LWG-3598
- LWG-3610 WIP
- LWG-3612
- LWG-3618
- LWG-3621 WIP
- LWG-3648
- LWG-3657
- LWG-3661

**Comment by CaseyCarter** [comment]
Thanks, @frederick-vs-ja! That's a ton of work. I put LWG-3632 under "not implemented" because I think we need a comment to explain why those constructors don't look like they do in the Standard to avoid confusion.

I've pushed a commit into #2549 to cleanup the comments for LWG-3601 and LWG-3616, after which I think we no longer need this tracking issue.
