### ISSUE TITLE
 July 2022 LWG issues

### ISSUE THREAD

**Issue by frederick-vs-ja** [microsoft/STL#2872]
(Previous meta-issue: #2527)

At the July 2022 virtual plenary meeting, [the resolutions of the following LWG issues](https://wg21.link/p2618r0) were merged into the C++ Working Paper.

# ❔ Not yet analyzed

# ❌ Not applicable

If an issue requires no action from implementers, we mark it as N/A. Categories:
* Pure wording clarifications with nothing to implement (these can be changes to non-normative text like examples and informative notes, or wording cleanups to normative text that don't impact observable behavior)
    * [x]  LWG-3659 Consider `ATOMIC_FLAG_INIT` undeprecation
      * MSVC STL has never deprecated this macro, and it might be impossible to reflect such deprecation in a library implementation
* Something that increases the restrictions placed on users, but implementers aren't expected to enforce those restrictions.
* Fixes for obviously broken wording, where implementers would have done the right thing anyways
    * [x]  LWG-3709 LWG-3703 was underly ambitious
    * [x]  LWG-3713 Sorted with respect to comparator (only)

# 😸 Already implemented
Sometimes we cite LWG issues in product code comments as we're implementing their proposed resolutions. When the resolutions are officially accepted, we should remove the citations (as the default assumption is that we're implementing what the Standard says). If something is especially subtle, we can convert the citation to mention the relevant Standard section.

Sometimes we should add test coverage - e.g. when the Standard begins requiring something that we were already doing, but weren't explicitly testing for.

* Already implemented, comments need to be removed and messages need to cite the Standard
    * [x] LWG-3670 *Cpp17InputIterator*s don't have integer-class difference types
    * [x] LWG-3705 Hashability shouldn't depend on `basic_string`'s allocator
* Implemented without comments
    * [x]  LWG-3687`expected<cv void, E>` move constructor should move
    * [x]  LWG-3703 Missing requirements for `expected<T, E> requires is_void<T>`
    * [x]  LWG-3704 LWG-2059 added overloads that might be ill-formed for sets
    * [x]  LWG-3708 `take_while_view::`_`sentinel`_'s conversion constructor should move

# 🩹 Patches an unimplemented feature
We should record this LWG issue in the GitHub issue tracking the feature. That way, we'll remember to verify it, but it doesn't represent net new work.
  * [x] LWG-3692 `zip_view::`_`iterator`_'s `operator<=>` is overconstrained
  * [x] LWG-3702 Should `zip_transform_view::`_`iterator`_ remove `operator<`?

# 🐞 Not yet implemented
  * Unprocessed
  * Filed a [GitHub issue labeled **LWG**](https://github.com/microsoft/STL/issues?q=is%3Aissue+label%3ALWG)
    * [x] LWG-3564 `transform_view::`_`iterator`_`<true>::value_type` and `iterator_category` should use `const F&`
    * [x] LWG-3617 `function`/`packaged_task` deduction guides and deducing `this`
      * Note that WG21-P1169 (static `operator()`) also changes these deduction guides.
    * [x] LWG-3701 Make `formatter<remove_cvref_t<const charT[N]>, charT>` requirement explicit
  * PR out for review
    * [ ]  LWG-3656 Inconsistent bit operations returning a count (implemented in #2880 )
    * [ ]  LWG-3671 `atomic_fetch_xor` missing from `stdatomic.h` (implemented in #2905 )
    * [ ]  LWG-3672 `common_iterator::operator->()` should return by value (implemented in #2907 )
    * [ ]  LWG-3683 `operator==` for `polymorphic_allocator` cannot deduce template argument in common cases (implemented in #2879 )
    * [ ]  LWG-3707 `chunk_view::`_`outer-iterator`_`::value_type::size` should return unsigned type (implemented in #2883 )
    * [ ]  LWG-3710 The `end` of `chunk_view` for input ranges can be `const` (implemented in #2878 )
    * [ ]  LWG-3711 Missing preconditions for `slide_view` constructor (implemented in #2946)
    * [ ]  LWG-3712 `chunk_view` and `slide_view` should not be `default_initializable` (implemented in #2943 )
    * [ ]  LWG-3715 `view_interface::empty` is overconstrained (implemented in #2946 )
    * [ ]  LWG-3719 Directory iterators should be usable with default sentinel (implemented in #2902 )
    * [ ]  LWG-3721 Allow an _arg-id_ with a value of zero for width in _std-format-spec_ (implemented in #2906 )
    * [ ]  LWG-3724 _`decay-copy`_ should be constrained (implemented in #2903 )

**Comment by frederick-vs-ja** [comment]
@StephanTLavavej @CaseyCarter feel free to edit this if my analyzation for any LWG issue is incorrect, or P/R for any issue hasn't been voted into the working paper.

**Comment by CaseyCarter** [comment]
Wow, thanks @frederick-vs-ja! This is a ton of work. I'm going to tag this (and any relevant PRs) as "blocked" until we actually get approval for the proposed resolutions in the WG21 virtual plenary on 2022-07-25, but folks should feel free to go ahead and submit/review such PRs.

**Comment by CaseyCarter** [comment]
I believe every issue has now been processed. We have PRs out for the majority, I've recorded the two that patch `zip` in #2252, filed issues for the three that don't yet have pull requests, and submitted a PR to cleanup comments for the two we implemented speculatively with comments.

Thanks to everyone, and again extra-special thanks to @frederick-vs-ja for filing this issue and a majority of the resolution PRs.
