### ISSUE TITLE
November 2022 LWG issues

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3214]
(Previous meta-issue: #2872)

At the November 2022 meeting, the following LWG issues were resolved in the C++ Working Paper.

:grey_question: Not yet analyzed
===
* Remaining issues:

:x:  Not applicable
===
If an issue requires no action from implementers, we mark it as N/A. Categories:

* Pure wording clarifications with nothing to implement (these can be changes to non-normative text like examples and informative notes, or wording cleanups to normative text that don't impact observable behavior)
  + [x] LWG-3600 Making `istream_iterator` copy constructor trivial is an ABI break
  + [x] LWG-3753 Clarify entity vs. freestanding entity
  + [x] LWG-3781 The exposition-only alias templates *`cont-key-type`* and *`cont-mapped-type`* should be removed
  + [x] LWG-3818 Exposition-only concepts are not described in library intro
  + [x] LWG-3822 Avoiding normalization in `filesystem::weakly_canonical`
  + [x] LWG-3824 Number of `bind` placeholders is underspecified
* Something that increases the restrictions placed on users, but implementers aren't expected to enforce those restrictions
* Fixes for obviously broken wording, where implementers would have done the right thing anyways
  + [x] LWG-3028 Container requirements tables should distinguish `const` and non-`const` variables
  + [x] LWG-3177 Limit permission to specialize variable templates to program-defined types
  + [x] LWG-3597 Unsigned integer types don't model *`advanceable`*
  + [x] LWG-3732 `prepend_range` and `append_range` can't be amortized constant time
  + [x] LWG-3738 Missing preconditions for `take_view` constructor
  + [x] LWG-3775 Broken dependencies in the *Cpp17Allocator* requirements
  + [x] LWG-3817 Missing preconditions on `forward_list` modifiers

:smile_cat: Already implemented
===
Sometimes we cite LWG issues in product code comments as we're implementing their proposed resolutions. When the resolutions are officially accepted, we should remove the citations (as the default assumption is that we're implementing what the Standard says). If something is especially subtle, we can convert the citation to mention the relevant Standard section. Sometimes we should add test coverage - e.g. when the Standard begins requiring something that we were already doing, but weren't explicitly testing for.

* Already implemented, comments need to be removed and messages need to cite the Standard
  + [ ] LWG-3569 `join_view` fails to support ranges of ranges with non-`default_initializable` iterators
  + [ ] LWG-3745 `std::atomic_wait` and its friends lack `noexcept`
  + [ ] LWG-3764 `reference_wrapper::operator()` should propagate `noexcept`
  + [ ] LWG-3766 `view_interface::cbegin` is underconstrained
  + [ ] LWG-3788 `jthread::operator=(jthread&&)` postconditions are unimplementable under self-assignment
* Implemented without comments
  + [x] LWG-3118 `fpos` equality comparison unspecified
  + [x] LWG-3636 `formatter<T>::format` should be `const`-qualified
  + [x] LWG-3747 `ranges::uninitialized_copy_n`, `ranges::uninitialized_move_n`, and `ranges::destroy_n` should use `std::move`
  + [x] LWG-3754 Class template `expected` synopsis contains declarations that do not match the detailed description
  + [x] LWG-3755 *`tuple-for-each`* can call user-defined `operator,`
  + [x] LWG-3757 What's the effect of `std::forward_like<void>(x)`?
  + [x] LWG-3759 `ranges::rotate_copy` should use `std::move`
  + [x] LWG-3765 `const_sentinel` should be constrained
  + [x] LWG-3770 `const_sentinel_t` is missing
  + [x] LWG-3782 Should `<math.h>` declare `::lerp`?
  + [x] LWG-3784 `std.compat` should not provide `::byte` and its friends
  + [x] LWG-3792 `__cpp_lib_constexpr_algorithms` should also be defined in `<utility>`
  + [x] LWG-3795 Self-move-assignment of `std::future` and `std::shared_future` have unimplementable postconditions
  + [x] LWG-3796 *`movable-box`* as member should use default-initialization instead of copy-initialization

:adhesive_bandage: Patches an unimplemented feature
===
We should record this LWG issue in the GitHub issue tracking the feature. That way, we'll remember to verify it, but it doesn't represent net new work.

* Recorded in #2910:
  + [x] LWG-3816 `flat_map` and `flat_multimap` should impose sequence container requirements
* Recorded in #2912:
  + [x] LWG-3751 Missing feature macro for `flat_set`
  + [x] LWG-3774 `<flat_set>` should include `<compare>`
* Recorded in #2914:
  + [x] LWG-3814 Add freestanding items requested by NB comments
* Recorded in #2919:
  + [x] LWG-3750 Too many papers bump `__cpp_lib_format`
* Recorded in #2252:
  + [x] LWG-3773 `views::zip_transform` still requires `F` to be `copy_constructible` when empty pack
* Recorded in #2923:
  + [x] LWG-3760 `cartesian_product_view::`*`iterator`*'s *`parent_`* is never valid
  + [x] LWG-3761 `cartesian_product_view::`*`iterator`*`::operator-` should pass by reference
  + [x] LWG-3801 `cartesian_product_view::`*`iterator`*`::`*`distance-from`* ignores the size of last underlying range
* Recorded in #2936:
  + [x] LWG-3762 `generator::`*`iterator`*`::operator==` should pass by reference
  + [x] LWG-3826 Redundant specification \[for overload of `yield_value`\]

:lady_beetle: Not yet implemented
===
* Filed a [GitHub issue labeled **LWG**](https://github.com/microsoft/STL/issues?q=is%3Aissue+label%3ALWG)
  + [x] LWG-3515 \[stacktrace.basic.nonmem\]: `operator<<` should be less templatized (filed #3217)
  + [x] LWG-3545 `std::pointer_traits` should be SFINAE-friendly
  + [x] LWG-3594 `inout_ptr` - inconsistent `release()` in destructor (filed #3218)
  + [x] LWG-3629 `make_error_code` and `make_error_condition` are customization points (filed #3216)
  + [x] LWG-3646 `std::ranges::view_interface::size` returns a signed type (filed #3219)
  + [x] LWG-3677 Is a *cv*-qualified `pair` specially handled in uses-allocator construction? (filed #3220)
  + [x] LWG-3717 `common_view::end` should improve `random_access_range` case (filed #3221)
  + [x] LWG-3736 `move_iterator` missing `disable_sized_sentinel_for` specialization (filed #3222)
  + [x] LWG-3737 `take_view::`*`sentinel`* should provide `operator-` (filed #3223)
  + [x] LWG-3743 `ranges::to`'s `reserve` may be ill-formed (filed #3224)
  + [x] LWG-3746 `optional`'s spaceship with `U` with a type derived from `optional` causes infinite constraint meta-recursion (filed #3225)
  + [x] LWG-3778 `vector<bool>` missing exception specifications (filed #3226)
  + [x] LWG-3785 `ranges::to` is over-constrained on the destination type being a range (filed #3227)
  + [x] LWG-3798 Rvalue reference and `iterator_category` (filed #3228)
  + [x] LWG-3823 Unnecessary precondition for `is_aggregate` (filed #3229)
* PR out for review

**Comment by fsb4000** [comment]
Implemented without comments:
[LWG-3636](https://cplusplus.github.io/LWG/issue3636) `formatter<T>::format` should be `const`-qualified
https://github.com/microsoft/STL/commit/7b2c54be012f998736ebb6b72c7804a3f6c5f8e5

**Comment by cpplearner** [comment]
> LWG-3750 Too many papers bump `__cpp_lib_format`

Patches an unimplemented feature: P2286R8 Formatting Ranges #2919

> LWG-3754 Class template `expected` synopsis contains declarations that do not match the detailed description

Implemented without comments

**Comment by JMazurkiewicz** [comment]
Implemented without comments:
[LWG-3765](https://cplusplus.github.io/LWG/issue3765) `const_sentinel` should be constrained (PR: #3043, commit: https://github.com/microsoft/STL/pull/3043/commits/ed53e6bd4e62a2109c3c51b53a983331b9aaab7f).

Should LWG-3811 be on this list?

**Comment by frederick-vs-ja** [comment]
Pure wording clarifications with nothing to implement:
- LWG-3753 Clarify entity vs. freestanding entity
- LWG-3781 The exposition-only alias templates _`cont-key-type`_ and _`cont-mapped-type`_ should be removed
- LWG-3818 Exposition-only concepts are not described in library intro
- LWG-3824 Number of `bind` placeholders is underspecified (nothing to be implemented in MSVC STL, the number has been documented [here](https://learn.microsoft.com/en-us/cpp/standard-library/1-object?view=msvc-170#remarks))

Fixes for obviously broken wording, where implementers would have done the right thing anyways (checking may be added in some cases):
- LWG-3028 Container requirements tables should distinguish `const` and non-`const` variables
- LWG-3177 Limit permission to specialize variable templates to program-defined types
- LWG-3597 Unsigned integer types don't model _`advanceable`_ (the title is wrong, which is my fault)
- LWG-3738 Missing preconditions for `take_view` constructor
- LWG-3775 Broken dependencies in the _Cpp17Allocator_ requirements
- LWG-3817 Missing preconditions on `forward_list` modifiers

Already implemented, comments need to be removed and messages need to cite the Standard:
- LWG-3545 `std::pointer_traits` should be SFINAE-friendly
- LWG-3745 `std::atomic_wait` and its friends lack `noexcept`
- LWG-3764 `reference_wrapper::operator()` should propagate `noexcept`

Implemented without comments:
- LWG-3118 `fpos` equality comparison unspecified
- LWG-3629 `make_error_code` and `make_error_condition` are customization points
- LWG-3747 `ranges::uninitialized_copy_n`, `ranges::uninitialized_move_n`, and `ranges::destroy_n` should use std::move (IIUC this got completed in #2964)
- LWG-3755 _`tuple-for-each`_ can call user-defined `operator,`
- LWG-3757 What's the effect of `std::forward_like<void>(x)`?
- LWG-3759 `ranges::rotate_copy` should use `std::move`
- LWG-3782 Should `<math.h>` declare `::lerp`?
- LWG-3784 `std.compat` should not provide `::byte` and its friends
- LWG-3792 `__cpp_lib_constexpr_algorithms` should also be defined in `<utility>`
- LWG-3795 Self-move-assignment of `std::future` and `std::shared_future` have unimplementable postconditions
- LWG-3796 _`movable-box`_ as member should use default-initialization instead of copy-initialization (the `repeat_view` part is being implemented in #3142, no comment added)

Patches an unimplemented feature:
- Patches for [P1642R11](https://wg21.link/p1642r11) #2914
  - LWG-3814 Add freestanding items requested by NB comments

**Comment by cpplearner** [comment]
> - [LWG-3629](https://cplusplus.github.io/LWG/issue3629) `make_error_code` and `make_error_condition` are customization points

Note that the resolution makes `make_error_code` & `make_error_condition` only found by ADL (not by regular unqualified lookup). I believe that this is *not* yet implemented.

**Comment by StephanTLavavej** [comment]
Thanks, I've incorporated all your findings! I was able to go through the remaining list and verify that most of those issues require implementation changes, so I've filed tracking issues for them. That leaves:

* LWG-3600 Making `istream_iterator` copy constructor trivial is an ABI break
  + I'm not sure if we need to make changes here.
* LWG-3822 Avoiding normalization in `filesystem::weakly_canonical`
  + This appears to be N/A (obviously broken wording) since it merely removes a suggestion for implementers?

**Comment by strega-nil-ms** [comment]
LWG-3600 &ndash; we don't have to do anything here. We don't explicitly define the copy constructor, so it's `constexpr` whenever the copy of `_Myival` and `_Myistr` is `constexpr`; since `_Myistr` is a pointer, that means all we care about is `_Myival`, and thus we have equivalence to the paragraph in the issue.

**Comment by strega-nil-ms** [comment]
LWG-3822 &ndash; I'm nearly certain that there is nothing for us to do here, however I'll take a further look tomorrow on the big screens 😸

**Comment by CaseyCarter** [comment]
> [LWG-3822](https://cplusplus.github.io/LWG/issue3822) – I'm nearly certain that there is nothing for us to do here, however I'll take a further look tomorrow on the big screens 😸

Yes. This issue is actually "we don't need to tell implementers to avoid doing things that are unnecessary." There's no functional change.

**Comment by CaseyCarter** [comment]
#3238 removes "LWG-XXXX" and `strengthened` comments for issues we already implement. With that, we're all done with classification. Thanks everyone!
