### ISSUE TITLE
February 2023 LWG issues

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#3437]
(Previous meta-issue: #3214)

At the February 2023 meeting, the following LWG issues were resolved in the C++ Working Paper.

:grey_question: Not yet analyzed
===
* Remaining issues:

:x:  Not applicable
===
If an issue requires no action from implementers, we mark it as N/A. Categories:

* Pure wording clarifications with nothing to implement (these can be changes to non-normative text like examples and informative notes, or wording cleanups to normative text that don't impact observable behavior)
  + [x] LWG-3441 Misleading note about calls to customization points
    - There's nothing to do here.
  + [x] LWG-3827 Deprecate `<stdalign.h>` and `<stdbool.h>` macros
    - There's nothing for us to do here. These `<meow.h>` headers aren't part of the repo. Our `<cstdalign>` does define `__alignas_is_defined` and our `<cstdbool>` gets `__bool_true_false_are_defined` from `<stdbool.h>`, but the `<cmeow>` wrappers are already deprecated in C++17 mode (we didn't bother to implement removal in C++20 mode) and it's unclear how the UCRT could emit deprecation warnings for these macros. This isn't worth spending more time on, given that deprecation warnings aren't required for conformance (and we already go quite far here).
  + [x] LWG-3828 Sync `intmax_t` and `uintmax_t` with C2x
  + [x] LWG-3871 Adjust note about `terminate`
* Something that increases the restrictions placed on users, but implementers aren't expected to enforce those restrictions
  + [x] LWG-3622 Misspecified transitivity of equivalence in \[unord.req.general\]
    - This is N/A because it increases restrictions on users without requiring implementers to enforce them.
  + [x] LWG-3645 `resize_and_overwrite` is overspecified to call its callback with lvalues
    - There's nothing for implementers to do here (it merely increases the restrictions for users).
* Fixes for obviously broken wording, where implementers would have done the right thing anyways
  + [x] LWG-3032 `ValueSwappable` requirement missing for `push_heap` and `make_heap`
  + [x] LWG-3756 Is the `std::atomic_flag` class signal-safe?
  + [x] LWG-3841 `<version>` should not be "*all freestanding*"
  + [x] LWG-3843 `std::expected<T, E>::value() &` assumes `E` is copy constructible
    - This is "naturally enforced" (as we attempt to copy) and the error messages should be sufficiently clear.

:smile_cat: Already implemented
===
Sometimes we cite LWG issues in product code comments as we're implementing their proposed resolutions. When the resolutions are officially accepted, we should remove the citations (as the default assumption is that we're implementing what the Standard says). If something is especially subtle, we can convert the citation to mention the relevant Standard section. Sometimes we should add test coverage - e.g. when the Standard begins requiring something that we were already doing, but weren't explicitly testing for.

* Already implemented, comments need to be removed and messages need to cite the Standard
  + [x] LWG-3085 `char_traits::copy` precondition too weak
  + [x] LWG-3664 LWG-3392 broke `std::ranges::distance(a, a + 3)`
  + [x] LWG-3723 `priority_queue::push_range` needs to `append_range`
  + [x] LWG-3742 `deque::prepend_range` needs to permute
  + [x] LWG-3807 The feature test macro for `ranges::find_last` should be renamed
  + [x] LWG-3857 `basic_string_view` should allow explicit conversion when only traits vary
  + [x] LWG-3867 Should `std::basic_osyncstream`'s move assignment operator be `noexcept`?
    - Created PR #3461 for all of these.
* Implemented without comments
  + [x] LWG-3811 `views::as_const` on `ref_view<T>` should return `ref_view<const T>`
    - Noted as implemented by #3234.
  + [x] LWG-3825 Missing compile-time argument `id` check in `basic_format_parse_context::next_arg_id`
    - Implemented by #2221.
  + [x] LWG-3842 Unclear wording for *precision* in *chrono-format-spec*
    - Implemented: https://github.com/microsoft/STL/blob/9ae1b3f1faada15feff9f0a0a9fa55c9dce532f5/stl/inc/chrono#L5301-L5313
    - We go beyond the Standard by using `treat_as_floating_point_v`. I think this is a remaining (small) defect in the Standardese.
    - When a new Working Paper is available, we could update the Standardese citation, but this is not absolutely necessary (as the stable name and paragraph number are unchanged, and the content of the paragraph hasn't changed *that* much).
  + [x] LWG-3866 Bad *Mandates* for `expected::transform_error` overloads
    - Implemented by #3361.

:adhesive_bandage: Patches an unimplemented feature
===
We should record this LWG issue in the GitHub issue tracking the feature. That way, we'll remember to verify it, but it doesn't represent net new work.

* Recorded in #2530:
  + [x] LWG-3834 Missing `constexpr` for `std::intmax_t` math functions in `<cinttypes>`
* Recorded in #2534:
  + [x] LWG-3819 `reference_`*`meow`*`s_from_temporary` should not use `is_`*`meow`*`ible`
* Recorded in #2909:
  + [x] LWG-3876 Default constructor of `std::layout_`*`meow`*`::mapping` misses precondition
* Recorded in #2910 and #2912:
  + [x] LWG-3786 Flat maps' deduction guides need to default `Allocator` to be useful
  + [x] LWG-3803 `flat_`*`meow`* constructors taking `KeyContainer` lack `KeyCompare` parameter
* Recorded in #2912:
  + [x] LWG-3879 `erase_if` for `flat_{,multi}set` is incorrectly specified
* Recorded in #2919:
  + [x] LWG-3839 `range_formatter`'s `set_separator`, `set_brackets`, and `underlying` functions should be `noexcept`
  + [x] LWG-3881 Incorrect formatting of container adaptors backed by `std::string`
* Recorded in #2923:
  + [x] LWG-3820 `cartesian_product_view::`*`iterator`*`::`*`prev`*  is not quite right
  + [x] LWG-3849 `cartesian_product_view::`*`iterator`*'s default constructor is overconstrained
* Recorded in #2956:
  + [x] LWG-3790 WG21-P1467R9 accidentally changed `nexttoward`'s signature

:lady_beetle: Not yet implemented
===
* Filed a [GitHub issue labeled **LWG**](https://github.com/microsoft/STL/issues?q=is%3Aissue+label%3ALWG)
  + [x] LWG-2195 Missing constructors for `match_results`
    - Filed #3411.
  + [x] LWG-2295 Locale name when the provided `Facet` is a `nullptr`
    - Filed #3463.
  + [x] LWG-3204 `sub_match::swap` only swaps the base class
    - Filed #3412.
  + [x] LWG-3631 `basic_format_arg(T&&)` should use `remove_cvref_t<T>` throughout
    - Filed #3460 _and_ noted in #2919 (we implement some but not all of the machinery this issue touches).
  + [x] LWG-3655 The *`INVOKE`* operation and `union` types
    - Filed #3424.
  + [x] LWG-3720 Restrict the valid types of *arg-id* for *width* and *precision* in *std-format-spec*
    - Filed #3425.
  + [x] LWG-3733 `ranges::to` misuses *`cpp17-input-iterator`*
    - Filed #3422.
  + [x] LWG-3734 Inconsistency in `inout_ptr` and `out_ptr` for empty case
    - Filed #3413.
  + [x] LWG-3769 `basic_const_iterator::operator==` causes infinite constraint recursion
    - Filed #3458.
  + [x] LWG-3821 `uses_allocator_construction_args` should have overload for *`pair-like`*
    - Filed #3415. Should wait for #3396 to be merged.
  + [x] LWG-3833 Remove specialization `template<size_t N> struct formatter<const charT[N], charT>`
    - Filed #3426.
  + [x] LWG-3836 `std::expected<bool, E1>` conversion constructor `expected(const expected<U, G>&)` should take precedence over `expected(U&&)` with `operator bool`
    - Filed #3433.
  + [x] LWG-3847 `ranges::to` can still return views
    - Filed #3417.
  + [x] LWG-3851 `chunk_view::`*`inner-iterator`* missing custom `iter_move` and `iter_swap`
    - Filed #3432.
  + [x] LWG-3853 `basic_const_iterator<volatile int*>::operator->` is ill-formed
    - Filed #3427.
  + [x] LWG-3860 `range_common_reference_t` is missing
    - Filed #3416.
  + [x] LWG-3862 `basic_const_iterator`'s `common_type` specialization is underconstrained
    - Filed #3428.
  + [x] LWG-3865 Sorting a range of `pair`s
    - Filed #3419.
  + [x] LWG-3869 Deprecate `std::errc` constants related to UNIX STREAMS
    - Filed #3420.
  + [x] LWG-3870 Remove *`voidify`*
    - Filed #3431.
  + [x] LWG-3872 `basic_const_iterator` should have custom `iter_move`
    - Filed #3429.
  + [x] LWG-3875 `std::ranges::repeat_view<T, IntegerClass>::`*`iterator`* may be ill-formed
    - Filed #3430.
  + [x] LWG-3877 Incorrect constraints on `const`-qualified monadic overloads for `std::expected`
    - Filed #3435.
  + [x] LWG-3878 `import std;` should guarantee initialization of standard iostreams objects
    - Filed #3436.
  + [x] LWG-3880 Clarify `operator+=` complexity for `{chunk,stride}_view::`*`iterator`*
    - Filed #3434.
* PR out for review
  + [x] LWG-3772 `repeat_view`'s piecewise constructor is missing preconditions
    - Implement an `_STL_VERIFY` check.
    -  PR #3462.
  + [x] LWG-3810 CTAD for `std::basic_format_args`
    - Filed #3414.
    - PR #3421.
  + [x] LWG-3848 `adjacent_view`, `adjacent_transform_view`, and `slide_view` missing `base` accessor
    - Filed #3409.
    - PR #3410.
    - Also recorded in #2252.
  + [x] LWG-3850 `views::as_const` on `empty_view<T>` should return `empty_view<const T>`
    - Filed #3418.
    - PR #3423.

**Comment by CaseyCarter** [comment]
Confirmed: LWG-3441 is definitely N/A. The resolution simply strikes the confusing "designated customization point" wording that LWG thinks  contributed only confusion.
Confirmed: LWG-3662 is N/A as well. The constraints on program-defined transparent equality comparators were insufficient, this makes them stronger.
Confirmed: LWG-3645 is N/A. User function objects must accept const-or-not lvalue-or-rvalue arguments - so implementations can pass whatever they like.

**Comment by CaseyCarter** [comment]
> * [LWG-3843](https://cplusplus.github.io/LWG/issue3843) `std::expected<T, E>::value() &` assumes `E` is copy constructible
>   * It looks like this is "naturally enforced" (as we attempt to copy), but we might want to add `static_assert`s.

I'm happy not to `static_assert`; I think the resulting error messages about being unable to copy will be clear enough.

**Comment by frederick-vs-ja** [comment]
> * This is "naturally enforced" (as we attempt to copy) and the error messages should be sufficiently clear.

This is currently _not_ enforced by MSVC (DevCom-1638273). I'll open a PR for workaround.
