### ISSUE TITLE
November 2023 LWG issues

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#4158]
(Previous meta-issue: #3778)

At the November 2023 meeting, the following LWG issues were resolved in the C++ Working Paper.

:grey_question: Not yet analyzed
===
* Remaining issues:
  + All done!

:x:  Not applicable
===
If an issue requires no action from implementers, we mark it as N/A. Categories:

* Pure wording clarifications with nothing to implement (these can be changes to non-normative text like examples and informative notes, or wording cleanups to normative text that don't impact observable behavior)
  + [x] LWG-2392 "character type" is used but not defined
  + [x] LWG-3203 `span` element access invalidation
  + [x] LWG-3957 \[container.alloc.reqmts\] The value category of `v` should be claimed
  + [x] LWG-3965 Incorrect example in \[format.string.escaped\]/3 for formatting of combining characters
    - Our implementation agrees with the corrected example.

* Something that increases the restrictions placed on users, but implementers aren't expected to enforce those restrictions
  + [x] LWG-3990 Program-defined specializations of `tuple` and `variant` can't be properly supported
* Fixes for obviously broken wording, where implementers would have done the right thing anyways
  + [x] LWG-3431 `<=>` for containers should require `three_way_comparable<T>` instead of `<=>`
  + [x] LWG-3951 \[expected.object.swap\]: Using `value()` instead of `has_value()`

:smile_cat: Already implemented
===
Sometimes we cite LWG issues in product code comments as we're implementing their proposed resolutions. When the resolutions are officially accepted, we should remove the citations (as the default assumption is that we're implementing what the Standard says). If something is especially subtle, we can convert the citation to mention the relevant Standard section. Sometimes we should add test coverage - e.g. when the Standard begins requiring something that we were already doing, but weren't explicitly testing for.

* Already implemented, comments need to be removed and messages need to cite the Standard
  + [x] LWG-3949 `atomic<bool>`'s trivial destructor dropped in C++17 spec wording
    - Filed #4164.
* Implemented without comments
  + [x] LWG-3305 `any_cast<void>`
    - We implemented dedicated `static_assert`s for this.
  + [x] LWG-3948 *`possibly-const-range`* and *`as-const-pointer`* should be `noexcept`
  + [x] LWG-3973 Monadic operations should be ADL-proof

:adhesive_bandage: Patches an unimplemented feature
===
We should record this LWG issue in the GitHub issue tracking the feature. That way, we'll remember to verify it, but it doesn't represent net new work.

* [x] LWG-3892 Incorrect formatting of nested ranges and tuples
  - Recorded in #2919.
* [x] LWG-3970 \[mdspan.syn\] Missing definition of `full_extent_t` and `full_extent`
  - Recorded in #3807.
* [x] LWG-3987 Including `<flat_meow>` doesn't provide `std::begin/end`
  - Recorded in #2910 and #2912.

:lady_beetle: Not yet implemented
===
* Filed a [GitHub issue labeled **LWG**](https://github.com/microsoft/STL/issues?q=is%3Aissue+label%3ALWG)
  + [x] LWG-3749 `common_iterator` should handle integer-class difference types
    - Filed #4163.
  + [x] LWG-3809 Is `subtract_with_carry_engine<uint16_t>` supposed to work?
    - Filed #4162.
  + [x] LWG-3897 `inout_ptr` will not update raw pointer to null
    - Filed #4160.
  + [x] LWG-3946 The definition of `const_iterator_t` should be reworked
    - Filed #4161.
  + [x] LWG-3947 Unexpected constraints on `adjacent_transform_view::base()`
    - Filed #4165.
  + [x] LWG-3953 `iter_move` for `common_iterator` and `counted_iterator` should return `decltype(auto)`
    - Filed #4157.
  + [x] LWG-3974 `mdspan::operator[]` should not copy `OtherIndexTypes`
    - Might already be implemented, filed #4166 to double-check.
  + [x] LWG-4001 `iota_view` should provide `empty`
    - Filed #4159.

* PR out for review
