### ISSUE TITLE
March 2024 LWG issues

### ISSUE THREAD

**Issue by frederick-vs-ja** [microsoft/STL#4491]
(Previous meta-issue: #4158)

At the March 2024 meeting, the following LWG issues [were resolved](https://wg21.link/p3180r0) in the C++ Working Paper.

# ❔ Not yet analyzed
* Remaining issues:
  * All done!

# ❌ Not applicable
If an issue requires no action from implementers, we mark it as N/A. Categories:

* Pure wording clarifications with nothing to implement (these can be changes to non-normative text like examples and informative notes, or wording cleanups to normative text that don't impact observable behavior)
  * [x]  LWG-4011 "_Effects_: Equivalent to return" in [span.elem]
  * [x]  LWG-4030 Clarify whether arithmetic expressions in [numeric.sat.func] are mathematical or C++
  * [x]  LWG-4036 `__alignof_is_defined` is only implicitly specified in C++ and not yet deprecated
    * Like LWG-3827, there's nothing for us to do here. Should we ping UCRT to implement macro deprecation? See also DevCom-10559200.
  * [x]  LWG-4043 `"ASCII"` is not a registered character encoding
* Something that increases the restrictions placed on users, but implementers aren't expected to enforce those restrictions
  * [x]  LWG-3975 Specializations of `basic_format_context` should not be permitted
  * [x]  LWG-4023 Preconditions of `std::basic_streambuf::setg`/`setp`
* Fixes for obviously broken wording, where implementers would have done the right thing anyways

# 😸 Already implemented
Sometimes we cite LWG issues in product code comments as we're implementing their proposed resolutions. When the resolutions are officially accepted, we should remove the citations (as the default assumption is that we're implementing what the Standard says). If something is especially subtle, we can convert the citation to mention the relevant Standard section. Sometimes we should add test coverage - e.g. when the Standard begins requiring something that we were already doing, but weren't explicitly testing for.

* Already implemented, comments need to be removed and messages need to cite the Standard
* Implemented without comments
  * [x]  LWG-4025 Move assignment operator of `std::expected<cv void, E>` should not be conditionally deleted
  * [x]  LWG-4031 `bad_expected_access<void>` member functions should be `noexcept`

# 🩹 Patches an unimplemented feature
We should record this LWG issue in the GitHub issue tracking the feature. That way, we'll remember to verify it, but it doesn't represent net new work.

* [x]  LWG-4038 `std::text_encoding::aliases_view` should have constexpr iterators
  * Recorded in #3791
* [x]  LWG-4045 `tuple` can create dangling references from _`tuple-like`_
  * Recorded in #2534

# 🐞 Not yet implemented
* Not yet implemented
* Filed a [GitHub issue labeled **LWG**](https://github.com/microsoft/STL/issues?q=is%3Aissue+label%3ALWG)
  * [x]  #4498
  * [x]  #4499
  * [x]  #4500
  * [x]  #4501
  * [x]  #4502
  * [x]  #4503
  * [x]  #4504
  * [x]  #4505
  * [x]  #4506
  * [x]  #4507
  * [x]  #4508
* PR out for review

**Comment by frederick-vs-ja** [comment]
Precondition checking for LWG-4023 and test coverages for LWG-4025/LWG-4031 may be wanted.

**Comment by StephanTLavavej** [comment]
> Precondition checking for LWG-4023 and test coverages for LWG-4025/LWG-4031 may be wanted.

After looking at these issues, while I wouldn't object to PRs addressing them, I don't think it's so urgent that we need tracking issues.

* LWG-4023 involves `protected` member functions of iostreams. These aren't directly called, and people implementing new iostreams need to be experts.
* LWG-4025 would involve writing test coverage to observe the difference between "defined as deleted" and "constraints" which seems like a ton of effort for little return, given that we automatically got this right to begin with.
* LWG-4031 would involve writing test coverage to observe the `noexcept`ness of `protected` member functions, which is doable but requires extra effort. We just `=default`ed them, getting this automatically correct, and I don't think we need to bother testing this.

(In general, test coverage is most valuable for things that were tricky to achieve, or that might regress due to compiler or library changes.)

I've filed tracking issues for everything else, so we can close this meta-issue. Thanks again for doing the *massive* work needed to understand our current status, and so rapidly too! :heart_eyes_cat: :white_check_mark: :tada:
