### ISSUE TITLE
GitHub migration

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#4699]
All tasks related to migrating our work from Microsoft-internal systems to GitHub.

# Build System
* [ ] #161
* [ ] #162
* [ ] Port the ARM64EC build.
* [ ] Port DLL export validation from MSBuild to CMake. (Or switch to `.def`.)
* [ ] Change the MSVC-internal MSBuild build system to invoke the STL's CMake build system.
* [ ] Delete `stl/msbuild` and celebrate!

# Tests
* [ ] Finish migrating `src/qa/VC/Libs/vcr/tests/cpp/Dev09_171913_tr1_windows_h_macros`
  + And resolve Microsoft-internal VSO-936680
* [ ] #797
* [ ] #798
* [ ] #820

# Documentation
* [ ] Write Contribution Guidelines.
* [ ] Drop the Roadmap.

# Issues
* [ ] Finish migrating bugs.
  + As of 2024-05-28: 107 bugs remain.
* [ ] Create bugs for vNext overhauls, collecting DevCom/VSO bugs (tagged vclibs-wcfb02) that were closed in the pre-GitHub Team Foundation Version Control vNext era.
* [ ] Finish migrating [`todo.docx`](https://microsoft.sharepoint.com/:w:/t/DD_VC/EUnJ45lUCylImM8MhamoZ6MBZPKI7aOQ8jnJix_D4TgRwg?e=bZ7xXE) to `enhancement` issues.
  + As of 2024-05-28: 5 pages remain.
* [ ] Migrate [`lwg_issues_to_file.docx`](https://microsoft.sharepoint.com/:w:/t/DD_VC/EVCtsKrXYqtJqIlKZ_UE1XIB_6eb8pD_dBYytxZZl_rKBQ?e=crTvYM) to `LWG issue needed` issues.
  + As of 2024-05-28: 2.5 pages remain.
* [ ] Migrate [`stl_requested_bugs.docx`](https://microsoft.sharepoint.com/:w:/t/DD_VC/EXS7I8x_n0NDteG-YPFnWTMBWyKX6BzY7iXSYleMyYxKhQ?e=tiehq9) somewhere (possibly the STL Wiki).
* [ ] #2271

# Done
* [x] Migrated `status.xlsx` to [microsoft.github.io/STL/](https://microsoft.github.io/STL/), powered by Chart.js.
* [x] #386
* [x] #639
* [x] #939
* [x] Switched the internal build to use boost-math standalone:
  + #2151
  + #3077 (also migrated a Special Math test)
* [x] Migrated tests from `vcr/tests/cpp` to `std`:
  + #2507
* [x] Unified libcxx's `expected_results.txt` and `skipped_tests.txt`:
  + #3484
