### ISSUE TITLE
Meta LWG issue: 2024-06 meeting

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#4759]
(Previous meta-issue: #4491)

At the June 2024 meeting, the following LWG issues were resolved in the C++ Working Paper.

:grey_question: Not yet analyzed
===
* Remaining issues:
  - All done!

:x:  Not applicable
===
If an issue requires no action from implementers, we mark it as N/A. Categories:

* Pure wording clarifications with nothing to implement (these can be changes to non-normative text like examples and informative notes, or wording cleanups to normative text that don't impact observable behavior)
  + [x] LWG-4076 `concat_view` should be freestanding
* Something that increases the restrictions placed on users, but implementers aren't expected to enforce those restrictions
* Fixes for obviously broken wording, where implementers would have done the right thing anyways

:smile_cat: Already implemented
===
Sometimes we cite LWG issues in product code comments as we're implementing their proposed resolutions. When the resolutions are officially accepted, we should remove the citations (as the default assumption is that we're implementing what the Standard says). If something is especially subtle, we can convert the citation to mention the relevant Standard section. Sometimes we should add test coverage - e.g. when the Standard begins requiring something that we were already doing, but weren't explicitly testing for.

* Already implemented, comments need to be removed and messages need to cite the Standard
* Implemented without comments

:adhesive_bandage: Patches an unimplemented feature
===
We should record this LWG issue in the GitHub issue tracking the feature. That way, we'll remember to verify it, but it doesn't represent net new work.

+ [x] LWG-4060 `submdspan` preconditions do not forbid creating invalid pointer
  - Recorded in #4516.
+ [x] LWG-4071 `reference_wrapper` comparisons are not SFINAE-friendly
  - Recorded in #4522.
+ [x] LWG-4079 Missing *Preconditions* in `concat_view::`*`iterator`*'s conversion constructor
  - Recorded in #4514.
+ [x] LWG-4082 `views::concat(r)` is well-formed when `r` is an `output_range`
  - Recorded in #4514.

:lady_beetle: Not yet implemented
===
* Filed a [GitHub issue labeled **LWG**](https://github.com/microsoft/STL/issues?q=is%3Aissue+label%3ALWG)
  + [x] LWG-3944 Formatters converting sequences of `char` to sequences of `wchar_t`
    - #4760
  + [x] LWG-4074 *`compatible-joinable-ranges`* is underconstrained
    - #4761
  + [x] LWG-4083 `views::as_rvalue` should reject non-input ranges
    - #4762
  + [x] LWG-4096 `views::iota(views::iota(0))` should be rejected
    - #4763
  + [x] LWG-4098 `views::adjacent<0>` should reject non-forward ranges
    - #4764
  + [x] LWG-4105 `ranges::ends_with`'s *Returns* misses difference casting
    - #4765
* PR out for review
  + [x] LWG-4061 Should `std::basic_format_context` be default-constructible/copyable/movable?
    - #4758
  + [x] LWG-4106 `basic_format_args` should not be default-constructible
    - #4757
