### ISSUE TITLE
Meta LWG issue: 2024-11 meeting

### ISSUE THREAD

**Issue by StephanTLavavej** [microsoft/STL#5109]
(Previous meta-issue: #4759)

At the November 2024 meeting, the following LWG issues were resolved in the C++ Working Paper.

:grey_question: Not yet analyzed
===
* Remaining issues:
  - All done!

:x:  Not applicable
===
If an issue requires no action from implementers, we mark it as N/A. Categories:

* Pure wording clarifications with nothing to implement (these can be changes to non-normative text like examples and informative notes, or wording cleanups to normative text that don't impact observable behavior)
  + [x] LWG-4064 Clarify that `std::launder` is not needed when using the result of `std::memcpy`
  + [x] LWG-4126 Some feature-test macros for fully freestanding features are not yet marked freestanding
  + [x] LWG-4141 Improve prohibitions on "additional storage"
* Something that increases the restrictions placed on users, but implementers aren't expected to enforce those restrictions
  + [x] LWG-4170 `contiguous_iterator` should require `to_address(I{})`
* Fixes for obviously broken wording, where implementers would have done the right thing anyways

:smile_cat: Already implemented
===
Sometimes we cite LWG issues in product code comments as we're implementing their proposed resolutions. When the resolutions are officially accepted, we should remove the citations (as the default assumption is that we're implementing what the Standard says). If something is especially subtle, we can convert the citation to mention the relevant Standard section. Sometimes we should add test coverage - e.g. when the Standard begins requiring something that we were already doing but weren't explicitly testing for.

* Already implemented, comments need to be removed, and messages need to cite the Standard
  + [x] LWG-4024 Underspecified destruction of objects created in `std::make_shared_for_overwrite/std::allocate_shared_for_overwrite`
    - Implemented by #4274, comment removal tracked by #5127
  + [x] LWG-4154 The Mandates for `std::packaged_task`'s constructor from a callable entity should consider decaying
    - Implemented by #4946, comment removal tracked by #5127
  + [x] LWG-3216 Rebinding the allocator before calling `construct`/`destroy` in `allocate_shared`
    - This also resolved LWG-3210 "`allocate_shared` is inconsistent about removing `const` from the pointer passed to allocator `construct` and `destroy`", which we've implemented since 2019. Comment removal tracked by #5127
* Implemented without comments
  + [x] LWG-4157 The resolution of LWG-3465 was damaged by WG21-P2167R3 (in `compare_partial_order_fallback`)
    - Implemented by #3258
  + [x] LWG-4088 `println` ignores the locale imbued in `std::ostream`
    - Implemented by #3337

:adhesive_bandage: Patches an unimplemented feature
===
* Recorded this LWG issue in the GitHub issue tracking the feature. That way, we'll remember to verify it, but it doesn't represent net new work.
  + [x] LWG-4085 `ranges::generate_random`'s helper lambda should specify the return type
    - Recorded in #4512
  + [x] LWG-4147 Precondition on `inplace_vector::emplace`
    - Recorded in #4766
  + [x] LWG-4134 Issue with Philox algorithm specification
    - Recorded in #4767
  + [x] LWG-4153 Fix extra "-1" for `philox_engine::max()`
    - Recorded in #4767
  + [x] LWG-4142 `format_parse_context::check_dynamic_spec` should require at least one type
    - Recorded in #3813
  + [x] LWG-4148 `unique_ptr::operator*` should not allow dangling references
    - Recorded in #2534

:lady_beetle: Not yet implemented
===
* Filed a [GitHub issue labeled **LWG**](https://github.com/microsoft/STL/issues?q=is%3Aissue+label%3ALWG)
  + [x] LWG-3436 `std::construct_at` should support arrays
    - #5110
  + [x] LWG-3899 `co_yield`ing elements of an lvalue `generator` is unnecessarily inefficient
    - #5111
  + [x] LWG-3900 The `allocator_arg_t` overloads of `generator::promise_type::operator new` should not be constrained
    - #5112
  + [x] LWG-3918 `std::uninitialized_move/_n` and guaranteed copy elision
    - #5113
  + [x] LWG-4027 *`possibly-const-range`* should prefer returning `const R&`
    - #5114
  + [x] LWG-4072 `std::optional` comparisons: constrain harder
    - #5115
  + [x] LWG-4112 *`has-arrow`* should require `operator->()` to be `const`-qualified
    - #5116
  + [x] LWG-4135 The helper lambda of `std::erase` for `list` should specify return type as `bool`
    - #5117
  + [x] LWG-4119 `generator::promise_type::yield_value(ranges::elements_of<R, Alloc>)`'s nested `generator` may be ill-formed
    - #5118
  + [x] LWG-3886 Monad mo' problems (in `optional` and `expected`)
    - #5119
  + [x] LWG-4084 `std::fixed` ignores `std::uppercase`
    - #5120
  + [x] LWG-4124 Cannot format `zoned_time` with resolution coarser than seconds
    - #5121
  + [x] LWG-4140 Useless default constructors for bit reference types
    - #5122
  + [x] LWG-4169 `std::atomic<T>`'s default constructor should be constrained
    - #5123
  + [x] LWG-4113 Disallow `has_unique_object_representations<Incomplete[]>`
    - #5124
  + [x] LWG-4144 Disallow `unique_ptr<T&, D>`
    - #5125
  + [x] LWG-4164 Missing guarantees for `forward_list` modifiers
    - #5126
  + [x] LWG-4014 LWG-3809 changes behavior of some existing `std::subtract_with_carry_engine` code
    - #5133
  + [x] LWG-4044 Confusing requirements for `std::print` on POSIX platforms
    - No action required for correctness on Windows, but filed performance followup #5134
* PR out for review

**Comment by frederick-vs-ja** [comment]
LWG-4024 is implemented by #4274. Comments should be removed.
LWG-4064 is  probably N/A for library implementations. It should be handled by compiler frontends.
LWG-4126 is N/A for out hosted implementation. We always provide these feature-macro in corresponding modes.
LWG-4135 is implemented by #4900. No comment added.
LWG-4141 is N/A or already implemented. The issue mainly makes the intent of designs more explicit.
LWG-4154 is implemented by #4946. Comments should be removed.
LWG-4157 is implemented by #3258. No comment added.

**Comment by StephanTLavavej** [comment]
Thanks! I've applied all of that, except that I filed #5117 because I noticed that it's not fully implemented.

**Comment by CaseyCarter** [comment]
> [LWG-4044](https://cplusplus.github.io/LWG/issue4044) Confusing requirements for `std::print` on POSIX platforms
> 
> * [@StephanTLavavej](https://github.com/StephanTLavavej) thinks this should have no effect for Windows; need to double-check

There exist terminals that can only display Unicode via a "native Unicode API", and terminals that can display Unicode simply via the normal means of dumping output. The intent of the issue is that only the former require the determination if a stream refers to such a terminal, and require flushing the "normal" output before invoking such a "native Unicode API" to output Unicode.

In real world terms, "native Unicode API" means "`WriteConsoleW` on Windows". Non-Windows platforms are supposed to ignore these instructions but it wasn't clear to them that they should, so the issue is trying to clarify that intent. 

Of course there are also terminals on Windows that are capable of displaying Unicode via the normal output mechanisms. My machine with the "Beta: Use UTF-8 for language support" feature activated defaults to codepage 65001 in terminals and doesn't need "native Unicode API" to output Unicode. At some point we should start detecting this condition and avoiding the mess of flushing `stdout` and transcoding to UTF-16 to call `WriteConsoleW`.
